apiVersion: v1
kind: Service
metadata:
  name: {{ template "local-ai.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "local-ai.labels" . | nindent 4 }}
{{- if .Values.service.annotations }}
  annotations:
  {{ toYaml .Values.service.annotations | nindent 4 }}
{{- end }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "local-ai.name" . }}
  type: "{{ .Values.service.type }}"
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8080
      name: http
